exclude:
  - tests
  - phpcs/TYPO3SniffPool

copy-left:
  Greg Sherwood <gsherwood@squiz.net>:
    - phpcs/PhpCodeQuality/Sniffs/Commenting/BlockCommentSniff.php
    - phpcs/PhpCodeQuality/Sniffs/Commenting/ClassCommentSniff.php
    - phpcs/PhpCodeQuality/Sniffs/Commenting/FileCommentSniff.php
    - phpcs/PhpCodeQuality/Sniffs/Commenting/FunctionCommentSniff.php
    - phpcs/PhpCodeQuality/Sniffs/Commenting/VariableCommentSniff.php
    - phpcs/PhpCodeQuality/Sniffs/Files/EncodingUtf8Sniff.php
    - phpcs/PhpCodeQuality/Sniffs/PHP/CommentedOutCodeSniff.php
    - phpcs/PhpCodeQuality/Sniffs/PHP/ForbiddenFunctionsSniff.php
    - phpcs/PhpCodeQuality/Sniffs/Strings/UnnecessaryStringConcatSniff.php
    - phpcs/PhpCodeQuality/Sniffs/WhiteSpace/WhitespaceAfterAsteriskSniff.php
  Marc McIntyre <mmcintyre@squiz.net>:
    - phpcs/PhpCodeQuality/Sniffs/Commenting/BlockCommentSniff.php
    - phpcs/PhpCodeQuality/Sniffs/Commenting/ClassCommentSniff.php
    - phpcs/PhpCodeQuality/Sniffs/Commenting/FileCommentSniff.php
    - phpcs/PhpCodeQuality/Sniffs/Commenting/FunctionCommentSniff.php
    - phpcs/PhpCodeQuality/Sniffs/Commenting/VariableCommentSniff.php
    - phpcs/PhpCodeQuality/Sniffs/Files/EncodingUtf8Sniff.php
    - phpcs/PhpCodeQuality/Sniffs/PHP/CommentedOutCodeSniff.php
    - phpcs/PhpCodeQuality/Sniffs/PHP/ForbiddenFunctionsSniff.php
    - phpcs/PhpCodeQuality/Sniffs/Strings/UnnecessaryStringConcatSniff.php
    - phpcs/PhpCodeQuality/Sniffs/WhiteSpace/WhitespaceAfterAsteriskSniff.php
