language: php
php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"

install:
    - cd phpcs && composer install --prefer-dist --dev

script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs --standard=PHPCQ/ruleset.phpunit.xml PHPCQ/Sniffs/
